### we are trying t-test to validate that is there any difference between sampled mean and population mean

# One sampled

In [1]:
import numpy as np

In [2]:
age=[10,20,30,35,44,32,31,33,34,35,36,33,32,65,22,33,34,33,37,36,35,36,76,33]

In [3]:
np.mean(age)

35.208333333333336

In [4]:
len(age)

24

In [5]:
sample_age=np.random.choice(age,7)

In [6]:
sample_age

array([32, 32, 35, 33, 22, 36, 33])

In [8]:
from scipy.stats import ttest_1samp

In [9]:
ttest,p_value=ttest_1samp(sample_age,35)

In [10]:
print(p_value)

0.12054370589939789


In [11]:
#if p_value is less than significant value < 0.05 then null hypothesis fails i.e there is a difference

In [16]:
#2nd example

In [18]:
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [24]:
_,p_value=stats.ttest_1samp(a=classA_ages,popmean=school_ages.mean())

In [25]:
p_value

1.139027071016194e-13

In [26]:
# we were comparing ages of school and classA

# Two sampled

In [30]:
np.random.seed(6)
classb_ages=stats.poisson.rvs(loc=18,mu=33,size=60)
#this means the age should start from 18 and mean should be 35
classb_ages.mean()

50.483333333333334

In [31]:
_,p_value=stats.ttest_ind(a=classA_ages,b=classb_ages,equal_var=False)

In [32]:
p_value

0.0010324920273110058

In [33]:
# therefore we reject the null hypothesis

# Paired T test

In [42]:
w1 = [25,30,40,50,30,40,35,55,65,52,70,63,54,43,45]

In [44]:
w2=w1+ stats.norm.rvs(scale=5,loc=-1.25,size=15)
print (w1)
print (w2)

[25, 30, 40, 50, 30, 40, 35, 55, 65, 52, 70, 63, 54, 43, 45]
[17.74324303 33.20826367 33.82636035 47.69686513 32.08078962 34.76875876
 28.77290088 53.1793642  70.60090762 56.2482667  75.75290728 63.67354022
 55.19142057 47.10154865 46.59276701]


In [45]:
_,p_value=stats.ttest_rel(a=w1,b=w2)

In [46]:
p_value

0.974743730549964

In [47]:
# null hypothesis is accepted

# Chi square test

In [49]:
import seaborn as sns
import pandas as pd

In [50]:
dataset=sns.load_dataset('tips')

In [51]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [53]:
dataset_table=pd.crosstab(dataset['smoker'],dataset['sex'])
dataset_table

sex     Male  Female
smoker              
Yes       60      33
No        97      54

In [54]:
#observed value
obs_value=dataset_table.values
print(obs_value)

[[60 33]
 [97 54]]


In [56]:
val=stats.chi2_contingency(dataset_table)
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 33.15983607],
        [97.15983607, 53.84016393]]))

In [57]:
#val 3 is the expected value

In [58]:
expected_value=val[3]

In [59]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_cols=len(dataset_table.iloc[0,0:2])
dof=(no_of_rows-1)*(no_of_cols-1)
print('degree of freedom',dof)
alpha=0.05

degree of freedom 1


In [61]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(obs_value,expected_value)])
chi_square_statics=chi_square[0]+chi_square[1]
chi_square_statics

0.001934818536627623

In [64]:
#p_value
p_value=1-chi2.cdf(chi_square_statics,df=dof)
p_value
#if p_value <= significant value reject null hypothesis i.e there is relation between two feature

0.964915107315732

In [65]:
critical_value=chi2.ppf(q=1-alpha,df=dof)
critical_value
#if critical value <= chi_square_statics reject null hypothesis

3.841458820694124